import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "../styles/global-syles.css";
import "../styles/swiper-styles.scss";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

const aeonik = localFont({
  src: [
    {
      path: "../../public/fonts/Aeonik/Aeonik-Light.otf",
      weight: "250",
      style: "normal",
    },
    {
      path: "../../public/fonts/Aeonik/Aeonik-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Aeonik/Aeonik-Regular.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/Aeonik/Aeonik-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-aeonik",
});

const neueMontreal = localFont({
  src: [
    {
      path: "../../public/fonts/PPNeueMontreal/PPNeueMontreal-Light.otf",
      weight: "250",
      style: "normal",
    },
    {
      path: "../../public/fonts/PPNeueMontreal/PPNeueMontreal-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/PPNeueMontreal/PPNeueMontreal-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/PPNeueMontreal/PPNeueMontreal-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-neue-montreal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${aeonik.variable} ${neueMontreal.variable} antialiased bg-dark text-white`}
      >
        {/* <Header /> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
